name: "Deploy"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:
  
  staging-deploy:
    name: "Cloudflare - Staging"
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://data-api-staging.cheqd.io/

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@2.0.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: '2.0.29'
          preCommands: npm ci
          command: publish --env staging
          secrets: |
            WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

  production-deploy:
    name: "Cloudflare - Production"
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://data-api.cheqd.io/

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@2.0.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: '2.0.29'
          preCommands: npm ci
          command: publish
          secrets: |
            WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
